### PR TITLE
Added the ability to find the token from the query params

### PR DESCRIPTION
**Pull request by elbanyaoui**
I know the JWT it's like a password and should not be appears in the URL but I think it is kind of useful in some situations like when using proxy servers or when testing

### CODE REVIEW

**Comment by carc1n0gen** [comment]
@elbanyaoui is there a reason you've decided to change the package vendor prefix throughout the readme and composer.json?

**Comment by elbanyaoui** [comment]
I forgot about this pull request, I closed it now, btw I changed the package prefix because I added a new rule to verify the request using the method(HTTP Verb) and the the path, and I need this in my projects so to facilitate the installation I changed it and added it to packagist.

more information here : https://packagist.org/packages/elbanyaoui/slim-jwt-auth

**Comment by tuupola** [comment]
You could also  make the custom rule composer installable and then install both.

```
$ composer install tuupola/slim-jwt-auth
$ composer install elbanyaoui/somerule
```

**Comment by elbanyaoui** [comment]
ok thanks I will look into that

**Pull request closed without merging**
