### PR TITLE
fix: failing to set "Rules" with constructor due to $this->rules changed to SplStack.

### PR DESCRIPTION
**Pull request by falanso**

### CODE REVIEW

**Comment by tuupola** [comment]
Hi, what problem does this PR fix? It kind of looks similar to an earlier commit https://github.com/tuupola/slim-jwt-auth/commit/db4d88b371a89bfb975e0042ff7ce4377b3edd2e.

**Comment by falanso** [comment]
because the following was not working anymore,
it gives calling push() on an array error.

```php
$app = new Slim\App;

$app->add(new Tuupola\Middleware\JwtAuthentication([
    "rules" => [
        new Tuupola\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/",
            "ignore" => []
        ]),
        new Tuupola\Middleware\JwtAuthentication\RequestMethodRule([
            "ignore" => ["OPTIONS"]
        ])
    ]
]));
```

**Comment by icetee** [comment]
I have this problem. I add `path` and `rules` to options. If I delete one, it works.

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "attribute" => "jwt",
    "path" => "/api",
    "ignore" => ["/api/auth"],
    "relaxed" => ["localhost", "whatsapp-api.local"],
    "secure" => true,
    "secret" => $app->getContainer()->settings['jwt']['secret'],
    "rules" => [
        new Tuupola\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/api",
            "passthrough" => ["/api/list", "/api/ping"]
        ]),
        new Tuupola\Middleware\JwtAuthentication\RequestMethodRule([
            "ignore" => ["OPTIONS"]
        ])
    ],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    }
]));
```

I get the errors:
```
Fatal error: Uncaught Error: Call to a member function push() on array in /home/vagrant/Code/_cf/kvm/api/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php on line 97
```

```
Error: Call to a member function push() on array in /home/vagrant/Code/_cf/kvm/api/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php on line 97
```

**Comment by tuupola** [comment]
The errors should not be visible to user, will check on that. I  also see a couple or problems. 

You should set the `path` and `ignore` either by using `path` and `ignore` settings or passing them in `rules`. Should not use both. I guess this could be documented better.

Another problem is that `RequestPathRule` does not have parameter called `passthrough`. It was renamed to `ignore` in 3.x. All the changes between 2.x and 3.x are explained in [UPGGRADING.md](https://github.com/tuupola/slim-jwt-auth/blob/3.x/UPGRADING.md).

In other words the code above should be either:

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "attribute" => "jwt",
    "path" => "/api",
    "ignore" => ["/api/auth", "/api/list", "/api/ping"],
    "relaxed" => ["localhost", "whatsapp-api.local"],
    "secure" => true,
    "secret" => $app->getContainer()->settings['jwt']['secret'],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    }
]));
```

or:

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "attribute" => "jwt",
    "relaxed" => ["localhost", "whatsapp-api.local"],
    "secure" => true,
    "secret" => $app->getContainer()->settings['jwt']['secret'],
    "rules" => [
        new Tuupola\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/api",
            "ignore" => ["/api/auth", "/api/list", "/api/ping"]
        ]),
        new Tuupola\Middleware\JwtAuthentication\RequestMethodRule([
            "ignore" => ["OPTIONS"]
        ])
    ],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    }
]));
```

**Comment by icetee** [comment]
Yes, course. I remove path attribute.

**Comment by tuupola** [comment]
@icetee did it fix the problem in your case?

**Comment by icetee** [comment]
Yep! I simple remove path attribute. But this PR working also.

**Comment by tuupola** [comment]
This has been fixed via #120.

**Pull request closed without merging**
