### PR TITLE
Update php-jwt to 5.0

### PR DESCRIPTION
**Pull request by BafS**
Hi,

php-jwt [does not have BC](https://github.com/firebase/php-jwt/releases/tag/v5.0.0) and all the tests pass, I just updated the composer for the version 5.

### CODE REVIEW

**Comment by BafS** [comment]
FYI the tests pass but the HHVM test does not pass because "HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`." on Travis.

**Comment by tuupola** [comment]
You mean it does not have a BC break? I was looking for a reason why they pumped up the main version number. It usually means there is a BC break, but maybe they are just not following semantic versioning.

**Comment by tuupola** [comment]
Merged, thanks!

**Comment by BafS** [comment]
@tuupola Yes I think that they don't follow the semantic versioning.
Thanks for your work :) !

**Comment by tuupola** [comment]
Released as [2.3.3](https://packagist.org/packages/tuupola/slim-jwt-auth#2.3.3).

**Pull request merged**
