### PR TITLE
Allow ignoring token error

### PR DESCRIPTION
**Pull request by izayoi256**
Usage

``` php

new JwtAuthentication([
    'error' => function ($request, $response, $arguments, $next) {
        if (true) {
            // Call next middleware anyway even if an error occured.
            return $next($request, $response);
        } else {
            // You can also return an error response as usual.
            return $response->getBody()->write('Foo');
        }
    },
]);

### CODE REVIEW

**Comment by tuupola** [comment]
What is the use case for this or what problem does it solve? Allowing an invalid token to authenticate is kind of same as password protection which allows both correct and incorrect passwords.

**Comment by izayoi256** [comment]
It allows OPTIONAL authentication operation.

``` php
class Security
{
    private $authenticated = false;

    public function authenticate($token)
    {
        $this->authenticated = isset($token->someVar);
        // or check something you want.
    }

    public function isAuthenticated(): bool
    {
        return $this->authenticated;
    }
}

$app = new \Slim\App();
$c = $app->getContainer();

$c['security'] = function ($c) {
    return new Security();
};

$c['JwtAuthentication'] = function ($c) {
    return new JwtAuthentication([
        'error' => function ($request, $response, $arguments, $next) {
            return $next($request, $response);
        },
        'callback' => function ($request, $response, $arguments) use ($c) {
            $c['security']->authenticate($arguments['decoded']);
        },
        // and other settings
    ]);
};

$this->add('JwtAuthentication');

$app->get('/path/to/optional_auth', function ($request, $response, $arguments) {
    if ($this->security->isAuthenticated()) {
        // do something only for authenticated user.
    }
    return $response->withStatus(200);
});

$app->run();
```

**Comment by tuupola** [comment]
You could use the [rules](https://github.com/tuupola/slim-jwt-auth#rules) to control whether the path is authenticated or not. Rules are just callables which return a boolean. If any of the rules returns boolean `false` the request will not be authenticated.

You could for example create a rule which checks if `Authentication: Bearer` header exists in the request. If not then do not authenticate. If yes then do authenticate. I find this better than allowing all, even broken tokens, to pass.

For inspiration you could check the included [default rules](https://github.com/tuupola/slim-jwt-auth/tree/2.x/src/JwtAuthentication).

**Comment by izayoi256** [comment]
Rule checking ```Authentication: Bearer``` header seems to be solution for me.

Thank you for taking your time responding!

**Pull request closed without merging**
